# process stress data generated by different CAD software to uniformly style
import sys
import os
import numpy as np
import tkinter
from tkinter import ttk
from tkinter import filedialog


def readHypermeshStyle(lines):
    stress = np.zeros((1, 6))
    # line_number = int(sline[0])
    n = len(lines)
    k = 0
    res = np.zeros((n, 6))
    stress = np.zeros(6)
    for line in lines:
        sline = line.split(',')
        # if this line contains data
        if sline[0].isdigit():
            digs = sline[1].split(' ')
            for i in range(6):
                stress[i] = float(digs[i])
            res[k] = stress
            k += 1
    return k, res[:k]


def readGuassStyle(lines):
    order = [0, 1, 2, 4, 5, 3]
    n = len(lines)
    k = 0
    res = np.zeros((n, 6))
    stress = np.zeros(6)
    for line in lines:
        sline = line.split()
        # if this line contains data
        try:
            float(sline[0])
        except ValueError:
            continue
        else:
            for i in range(6):
                stress[order[i]] = float(sline[i])
            res[k] = stress
            k += 1
    return k, res[:k]


def process(data_format):
    file_name = filedialog.askopenfilename(
        filetypes=[('csv', '*.csv'), ('txt', '.txt')])
    path = os.path.split(file_name)[0]
    with open(file_name, 'r') as fin:
        header = fin.readline()
        lines = fin.readlines()
        if header.find("GAUSS") >= 0:
            k, res = readGuassStyle(lines)
            type = "node"
        else:
            k, res = readHypermeshStyle(lines)
            type = "element"
        # header = str(k)
        save_file_name = filedialog.asksaveasfilename(
            filetypes=[("csv", "*.csv")], initialdir=path)
        if len(sys.argv) > 2:
            np.savetxt(save_file_name, res, fmt="%.4e",
                       delimiter=' ', header=sys.argv[2]+" " + str(k))
        else:
            np.savetxt(save_file_name, res, fmt="%.4e",
                       delimiter=' ', header=type+" " + str(k))


if __name__ == "__main__":
    root = tkinter.Tk()

    comvalue = tkinter.StringVar()
    format_box = ttk.Combobox(
        root, textvariable=comvalue, state='readonly')
    format_box["values"] = ("hypermesh", "GAUSS")
    format_box.current(0)
    format_box.grid(column=1, row=1)

    open_button = tkinter.Button(
        root, text="Open stress field file",
        command=lambda: process(format_box.get()))
    open_button.grid(column=1, row=0)

    root.mainloop()
